### ISSUE TITLE
Issue in Exercise - 6

### ISSUE THREAD

**Issue by Shivashant25** [microsoft/MCW-Internet-of-Things#41] opened 2021-11-18 13:43 UTC
In Exercise - 6> Task - 2> step - 26, The edgeAgent status is in Failed state state.  According to the lab guide it should be in running state.

![image](https://user-images.githubusercontent.com/81952290/142426510-fff8753a-ae6c-4204-abe7-759f023a7e46.png)

We tried checking the logs and we found a permission denied error. We ran chmod 777 command and gave all permission to `/etc/aziot/config.toml` file. But still we are facing the same issue. Please look into this.

![image](https://user-images.githubusercontent.com/81952290/142426453-a1bd3fcd-e134-4619-88ef-df4be6be3845.png)

**Comment by codingbandit** [comment] 2021-11-18 16:56
Hi @Shivashant25 - I was unable to reproduce your error. You should not have had to perform any CHMOD on files. Please revisit the configuration file and ensure the file is properly formatted.

On the edited lines, you may need to remove preceding spaces or trailing comments. Please review, and reapply the configuration to see if the problem still persists. If one of these things solved your issue, I will add clarification text accordingly.

![image](https://user-images.githubusercontent.com/3979478/142460830-be4b69f1-9f07-4562-a759-43ece3acc74f.png)

**Comment by Shivashant25** [comment] 2021-11-19 06:48
Hi @codingbandit , I had removed the comment and I had formatted the code in the same way how it is mentioned in the lab guide. I performed the task multiple times but still the issue existed.

![image](https://user-images.githubusercontent.com/81952290/142577656-64bfd946-8065-42fc-9566-c4187ff9b1fb.png)

![image](https://user-images.githubusercontent.com/81952290/142577671-88c832a1-76e0-4385-8ffd-9db399b4f678.png)

**Comment by codingbandit** [comment] 2021-11-19 15:40
It looks as if something may have gone awry with the VM. Could you delete the assets relative to the vm and attempt a new installation ? I would also recommend removing the individual enrollment and the edge device in the IoT Hub (if it's there).  
![image](https://user-images.githubusercontent.com/3979478/142649938-f27781a8-a8cf-4245-b33c-f20f52bb8100.png)

**Comment by DawnmarieDesJardins** [comment] 2021-11-29 20:50
@Shivashant25 - Hello!  Are you able to complete the lab with the suggestions above?

**Comment by DawnmarieDesJardins** [comment] 2021-12-03 20:32
No additional comments received closing issue.  Please reopen if needed

**Closed by DawnmarieDesJardins** 2021-12-03 20:32 UTC
